test: add JUnit results for Dashboard e2e tests
ceph/ceph-build pull request #1648
Opened 2020-08-24 16:06 UTC by epuertat

Ceph changes brought by https://github.com/ceph/ceph/pull/36771

Fixes: https://tracker.ceph.com/issues/47118
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

2020-08-26 08:52 UTC, LenzGr approved these changes
:+1: thanks!

2020-08-27 11:19 UTC, callithea approved these changes

2020-09-29 15:22 UTC, djgalloway commented on ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
> +              TERM=xterm-256color
Why the extra spacing?

2020-09-29 15:52 UTC, epuertat commented on ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
> +              TERM=xterm-256color
Unintentional... Will fix it. Thanks!

2020-09-30 14:33 UTC, djgalloway commented
jenksin test

2020-09-30 14:34 UTC, djgalloway commented
jenkins test

2020-09-30 14:37 UTC, djgalloway requested changes

2020-09-30 14:37 UTC, djgalloway commented on ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
> +          results: **/reports/*.xml
I think asterisks need to be in quotes

2020-09-30 14:41 UTC, epuertat commented on ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
> +          results: **/reports/*.xml
You're right! Thanks!

2020-09-30 14:59 UTC, djgalloway approved these changes

2020-09-30 15:13 UTC, epuertat commented
@djgalloway as https://github.com/ceph/ceph/pull/36771 has already been merged, if you're ok with this, we can merge it and see how JUnit tests start being reported for Dashboard PRs.

2020-09-30 15:38 UTC, merged

2020-09-30 16:14 UTC, epuertat commented
Thanks @djgalloway !

2020-10-01 09:14 UTC, epuertat commented
Let's revert this, as it is causing errors in all jobs:

> Recording test results
> Agent went offline during the build
> ERROR: Connection was broken: java.nio.channels.ClosedChannelException
> 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
> 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
> 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
> 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
> 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
> 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
> 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
> 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
> 	at hudson.remoting.Channel.close(Channel.java:1502)
> 	at hudson.remoting.Channel.close(Channel.java:1455)
> 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:874)
> 	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:110)
> 	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:765)
> 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
> 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Build step 'Publish JUnit test result report' marked build as failure
> ERROR: Step ?Publish Cobertura Coverage Report? failed: no workspace for ceph-pull-requests #60996