Add ramen-dr job
ceph/ceph-build pull request #2138
Opened 2023-06-07 09:08 UTC by rakeshgm

This is an initial attempt to run ramendr/ramen e2e tests which should trigger for every PR. 
This PR will only run unit tests for now. 
Ramen Repo: https://github.com/RamenDR/ramen.git

2023-06-07 09:08 UTC, rakeshgm commented on ramen-pull-requests/config/definations/ramen-pull-requests.yaml
> +          url: https://github.com/rakeshgm/ramen/
I have added my fork for testing purposes

2023-06-07 09:09 UTC, rakeshgm commented on ramen-pull-requests/config/definations/ramen-pull-requests.yaml
> +          url: https://github.com/rakeshgm/ramen.git
added my fork for testing purposes

2023-06-07 17:59 UTC, dmick commented
Good start.  You'll need to clean up anything you install, too.  A few notes:

* is installing go from a tarball really the right way to install go?  Are there not distro packages?

* if you make the git repo a variable, you can give a default of your workspace for now, and then just change it when you're ready with the job

* have you tested build/build on a clean installed image (container or vm, maybe)?

2023-06-08 17:19 UTC, rakeshgm commented
so installation from Tarball is what the official document says. [doc](https://go.dev/doc/installl). 
I will make the remaining changes

2023-06-21 03:53 UTC, dmick reviewed
What triggers this build?

2023-06-21 06:35 UTC, rakeshgm commented
> What triggers this build?

mostly pull-requests to the repo.

2023-06-21 23:31 UTC, dmick requested changes
I pulled the branch locally and tested pushing it to the server.  Noticed a few minor things:

1) name the file .yml like all the others (rather than .yaml)
2) Title the pull request "Add ramen-pull-requests" (which is the name of the actual job)
3) change the commit message to describe what the job does and for what purpose; the fact that it's the initial change is obvious from the git history, so note what ramen is and what role it serves in ceph

2023-06-21 23:36 UTC, dmick commented
I pushed the job to the jenkins server by hand.  It failed because it ran on a non-dnf system; you'll need to add labels to select the right sort of build host.  I suspect you want something like either 'centos8' or 'centos9'.  Also, I doubt it needs to be "huge".  Does/will this need testing on both x86_64 and arm64?

Here's the build log: https://jenkins.ceph.com/job/ramen-pull-requests/1/consoleFull

2024-11-12 08:22 UTC, closed without merging